language: ruby
rvm:
  - 2.4.1

script: bash ./deploy.sh

branches:
  only:
  - master

env:
  global:
  - ENCRYPTION_LABEL: "1cca17101aeb"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"

sudo: false

cache: bundler
